# Makefile.dep created Sat May 11 19:54:13 PDT 2019
debug.o: debug.cpp debug.h util.h util.tcc
util.o: util.cpp debug.h util.h util.tcc
main.o: main.cpp listmap.h xless.h xpair.h listmap.tcc debug.h util.h \
  util.tcc
